source :rubyforge
gem 'sinatra', '1.1.0'
gem 'thin', '1.2.7'
gem 'haml', '3.1.6'
gem 'sass', '3.2.1'
gem 'json', '1.7.5'
gem 'coffee-script', '2.2.0'
gem 'guard'
gem 'guard-rspec'
gem 'rake'
gem 'rspec'
gem 'growl'
gem 'shotgun'
